# AlertManager Configuration for Lanka Platform
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@lanka.platform'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        alertname: MemoryLeakDetected
      receiver: 'memory-alerts'
      repeat_interval: 15m

# Receivers configuration
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:4000/api/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: '${WEBHOOK_USERNAME:-admin}'
            password: '${WEBHOOK_PASSWORD:-admin123}'

  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL:-ops@lanka.platform}'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} on {{ .GroupLabels.service }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          
          Description:
          {{ range .Alerts }}
          - {{ .Annotations.description }}
          {{ end }}
          
          Labels:
          {{ range .CommonLabels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Runbook: {{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Service:* {{ .GroupLabels.service }}
          *Severity:* {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_WARNING:-dev@lanka.platform}'
        subject: '⚠️  WARNING: {{ .GroupLabels.alertname }} on {{ .GroupLabels.service }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          
          Description:
          {{ range .Alerts }}
          - {{ .Annotations.description }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: '⚠️  Warning: {{ .GroupLabels.alertname }}'
        text: |
          *Service:* {{ .GroupLabels.service }}
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          {{ end }}

  - name: 'memory-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_MEMORY:-dev@lanka.platform}'
        subject: '💾 MEMORY: {{ .GroupLabels.alertname }} on {{ .GroupLabels.service }}'
        body: |
          Memory Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

# Templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'
