apiVersion: v1
kind: Namespace
metadata:
  name: lanka-platform
  labels:
    name: lanka-platform
    app.kubernetes.io/name: lanka-platform
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: lanka-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: lanka-staging
  labels:
    name: lanka-staging
    app.kubernetes.io/name: lanka-platform
    app.kubernetes.io/instance: staging
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: lanka-platform
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: lanka-development
  labels:
    name: lanka-development
    app.kubernetes.io/name: lanka-platform
    app.kubernetes.io/instance: development
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: lanka-platform
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: monitoring
    environment: cluster-wide
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    name: ingress-system
    app.kubernetes.io/name: ingress-system
    app.kubernetes.io/component: ingress
    environment: cluster-wide